#DB dev configuration  [Replace with your actual RDS endpoint, database name, username, and password]
spring.datasource.url=jdbc:postgresql://<YOUR_RDS_ENDPOINT>:5432/<DB_NAME>
spring.datasource.username=<YOUR_USERNAME>
spring.datasource.password=<YOUR_PASSWORD>

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#SMTP Configuration for Gmail
spring.mail.username=<YOUR_GMAIL>
spring.mail.password=<YOUR_APP_PASSWORD>

#Security Configuration
jwt.secretKey=<YOUR_JWT_SECRET>